import streamlit as st
import pandas as pd
import sys, os, tempfile
import sqlite3

PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
if PROJECT_ROOT not in sys.path:
    sys.path.insert(0, PROJECT_ROOT)

from dashboard.data_access import get_events_table, clear_demo_data, DB_PATH

SAMPLE_DATASET_PATH = os.path.join(
    os.path.dirname(os.path.dirname(__file__)),
    "demo_data", "sample_dataset.csv"
)

def _render_inline_detail(inv_id: int):
    """Render investigation detail inline on this page."""
    from dashboard.data_access import get_investigation_detail
    import plotly.express as px

    data = get_investigation_detail(inv_id)
    if data is None:
        st.error(f"Investigation #{inv_id} not found.")
        return

    inv = data["investigation"]
    evidence = data["evidence"]
    recommendation = data["recommendation"]
    summary = data["summary"]

    col1, col2, col3 = st.columns(3)

    with col1:
        st.markdown(f"**Store:** {inv['store_name']}")
        st.markdown(f"**Category:** {inv['category_name']}")
        st.markdown(f"**Week:** {inv['investigation_date']}")

    conf_score = inv["confidence_score"]
    conf_color = "#2ecc71" if conf_score >= 0.7 else "#f39c12" if conf_score >= 0.4 else "#e74c3c"
    conf_label = "High" if conf_score >= 0.7 else "Medium" if conf_score >= 0.4 else "Low"

    with col2:
        st.markdown("**Confidence Score:**")
        st.markdown(
            f"<h2 style='color:{conf_color}'>{conf_score:.1%} ({conf_label})</h2>",
            unsafe_allow_html=True
        )

    with col3:
        st.markdown("**Evidence Coverage:**")
        st.markdown(f"<h2>{inv['evidence_coverage']}</h2>", unsafe_allow_html=True)

    st.divider()

    if recommendation is None:
        st.warning("⚠️ Insufficient evidence — no recommendation generated for this investigation.")
        return

    st.subheader("📊 Evidence Breakdown")
    ev_df = pd.DataFrame(evidence)
    ev_df["analyzer_score"] = ev_df["analyzer_score"].fillna(0.0)
    ev_df = ev_df.sort_values("rank")

    col_chart, col_table = st.columns([2, 1])

    with col_chart:
        fig = px.bar(
            ev_df, x="analyzer_score", y="analyzer_name", orientation="h",
            color="analyzer_score",
            color_continuous_scale=["#e74c3c", "#f39c12", "#2ecc71"],
            range_color=[0, 1],
            labels={"analyzer_score": "Score", "analyzer_name": "Analyzer"},
        )
        fig.update_layout(
            showlegend=False,
            coloraxis_showscale=False,
            margin=dict(l=0, r=0, t=10, b=0),
            height=300
        )
        st.plotly_chart(fig, use_container_width=True)

    with col_table:
        display_ev = ev_df[["rank", "analyzer_name", "analyzer_score"]].copy()
        display_ev["analyzer_score"] = display_ev["analyzer_score"].apply(lambda x: f"{x:.3f}")
        display_ev.columns = ["Rank", "Analyzer", "Score"]
        st.dataframe(display_ev, use_container_width=True, hide_index=True)

    st.divider()

    st.subheader("💡 Recommendation")
    priority_icon = {"immediate": "🔴", "short-term": "🟡", "monitor": "🟢"}.get(
        recommendation["priority"], "⚪"
    )

    st.markdown(
        f"""
        <div style='background:#1e1e2e;padding:20px;border-radius:10px;border-left:4px solid #7c3aed'>
        <p style='font-size:18px;margin:0'>{recommendation['action']}</p>
        <p style='margin:8px 0 0 0;color:#aaa'>
            {priority_icon} Priority: <b>{recommendation['priority'].title()}</b>
        </p>
        <p style='margin:8px 0 0 0;color:#aaa;font-size:13px'>{recommendation['rationale']}</p>
        </div>
        """,
        unsafe_allow_html=True
    )

    st.divider()

    st.subheader("🤖 AI Business Summary")
    if summary:
        st.info(summary["summary_text"])
        st.caption(f"Generated by: {summary['generated_by']}")
    else:
        st.caption("No AI summary available for this investigation.")
        if st.button("✨ Generate AI Summary", key=f"gen_summary_{inv_id}"):
            with st.spinner("Generating..."):
                from investigation_engine.openrouter_summary import generate_summary_for_one_investigation
                res = generate_summary_for_one_investigation(inv_id, DB_PATH)
                if res["status"] == "OK":
                    st.info(res["summary"])
                else:
                    st.error(f"Failed: {res['error']}")


with st.sidebar:
    st.image("https://img.icons8.com/fluency/96/combo-chart.png", width=60)
    st.title("DecisionLens")
    st.caption("Retail KPI Root Cause Investigation")
    st.divider()

    if st.button("🏠 Overview", use_container_width=True):
        st.switch_page("pages/1_Overview.py")
    if st.button("📋 Events", use_container_width=True):
        st.switch_page("pages/2_Events.py")
    if st.button("🔬 Investigation Detail", use_container_width=True):
        st.switch_page("pages/3_Investigation_Detail.py")
    if st.button("📈 Analytics", use_container_width=True):
        st.switch_page("pages/4_Analytics.py")
    if st.button("🧪 Try It Yourself", use_container_width=True, type="primary"):
        st.switch_page("pages/5_Try_It_Yourself.py")

    st.divider()


def _run_live_pipeline(csv_path: str, progress_callback=None) -> dict:
    import sqlite3

    from preprocessing.preprocessing_engine import run_preprocessing
    from kpi_engine.kpi_engine import compute_weekly_kpis
    from anomaly_detection.business_filter import apply_business_filter
    from anomaly_detection.isolation_forest_detector import detect_anomalies
    from anomaly_detection.correlation_analyzer import tag_correlations
    from anomaly_detection.business_event import build_business_events
    from database.db_manager import initialize_schema, get_connection
    from database.db_manager import get_or_create_store, get_or_create_category
    from investigation_engine.evidence_aggregator import run_all_analyzers_and_aggregate
    from investigation_engine.openrouter_summary import generate_summary_for_one_investigation

    def update_progress(percent, message):
        if progress_callback:
            progress_callback(percent, message)

    errors = []

    if not os.path.exists(csv_path):
        return {
            "status": "FAILED",
            "errors": [f"File not found: {csv_path}. Please re-upload your file."]
        }

    update_progress(5, "Phase 1 of 7: Reading dataset...")
    df_raw = pd.read_csv(csv_path, encoding="latin1")

    update_progress(12, "Phase 1 of 7: Preprocessing and mapping columns...")
    prep = run_preprocessing(df_raw)

    if prep["status"] != "OK":
        return {"status": "FAILED", "errors": ["Preprocessing failed"]}

    df = prep["data"]

    update_progress(22, "Phase 2 of 7: Computing weekly KPIs...")
    weekly_kpis = compute_weekly_kpis(df)

    update_progress(35, "Phase 3 of 7: Detecting anomalies...")
    filtered, _ = apply_business_filter(
        weekly_kpis,
        group_cols=["Store", "Category"]
    )
    anomaly_df, _ = detect_anomalies(
        filtered,
        group_cols=["Store", "Category"]
    )

    update_progress(45, "Phase 4 of 7: Grouping anomalies into business events...")
    tagged = tag_correlations(anomaly_df)
    events = build_business_events(tagged)

    candidate_targets = {}

    for event in events:
        year, week = event["year"], event["week"]

        score_lookup = {
            (row["Store"], row["Category"]): row.get("anomaly_score", 0.5)
            for row in event["anomaly_rows"]
        }

        for store, category in event["affected_groups"]:
            key = (store, category, year, week)
            anomaly_score = score_lookup.get((store, category), 0.5)

            if (
                key not in candidate_targets
                or anomaly_score > candidate_targets[key]["anomaly_score"]
            ):
                candidate_targets[key] = {
                    "store": store,
                    "category": category,
                    "year": year,
                    "week": week,
                    "anomaly_score": anomaly_score,
                }

    ranked_targets = sorted(
        candidate_targets.values(),
        key=lambda target: target["anomaly_score"],
        reverse=True,
    )

    total_detected = len(ranked_targets)
    large_dataset_mode = len(df) > 30000

    if large_dataset_mode:
        investigation_targets = ranked_targets[:50]
        update_progress(
            50,
            f"Large dataset mode: {total_detected} anomalies detected. "
            f"Investigating top {len(investigation_targets)} by score...",
        )
    else:
        investigation_targets = ranked_targets
        update_progress(
            50,
            f"Phase 5 of 7: Preparing {len(investigation_targets)} investigations...",
        )

    initialize_schema(DB_PATH)
    conn = get_connection(DB_PATH)
    cursor = conn.cursor()

    total_investigations = 0
    total_targets = len(investigation_targets)

    for current_target, target in enumerate(investigation_targets, start=1):
        store = target["store"]
        category = target["category"]
        year = target["year"]
        week = target["week"]

        progress_value = 50 + int(
            (current_target / max(total_targets, 1)) * 35
        )

        update_progress(
            progress_value,
            f"Phase 5 of 7: Investigating anomaly "
            f"{current_target} of {total_targets}...",
        )

        normalized_score = max(
            0.0,
            min(1.0, 0.5 + target["anomaly_score"]),
        )

        try:
            report = run_all_analyzers_and_aggregate(
                df,
                store=store,
                category=category,
                year=year,
                week=week,
                business_event_anomaly_score=normalized_score,
                kpi_correlation_strong=True,
            )

            store_id = get_or_create_store(conn, report.store)
            category_id = get_or_create_category(conn, report.category)
            investigation_date = f"{report.year}-W{report.week:02d}"

            cursor.execute("""
                INSERT INTO investigations (
                    store_id, category_id, investigation_date, year, week,
                    metric, confidence_score, evidence_coverage, coverage_count,
                    total_analyzers, status, source
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """, (
                store_id, category_id, investigation_date,
                report.year, report.week, "Revenue",
                report.confidence_score, report.get_evidence_coverage_string(),
                report.coverage_count, report.total_analyzers, "open", "demo_upload",
            ))

            investigation_id = cursor.lastrowid

            for rank, ev in enumerate(report.evidence, start=1):
                cursor.execute("""
                    INSERT INTO evidence (
                        investigation_id, analyzer_name, analyzer_score,
                        sufficient_data, description, rank
                    ) VALUES (?, ?, ?, ?, ?, ?)
                """, (
                    investigation_id, ev["analyzer"], ev["score"],
                    1 if ev["sufficient_data"] else 0,
                    ev.get("reason", "") if not ev["sufficient_data"] else "",
                    rank,
                ))

            conn.commit()
            total_investigations += 1

        except Exception as e:
            errors.append(str(e))
    conn.close()

    update_progress(87, "Phase 6 of 7: Creating recommendations...")

    conn3 = sqlite3.connect(DB_PATH)
    cur3 = conn3.cursor()

    cur3.execute("""
        SELECT investigation_id
        FROM investigations
        WHERE source = 'demo_upload'
        AND investigation_id NOT IN (
            SELECT investigation_id FROM recommendations
        )
    """)

    demo_inv_ids = [row[0] for row in cur3.fetchall()]
    conn3.close()

    from investigation_engine.recommendation_engine import (
        _priority_from_confidence,
        ACTION_TEMPLATES,
        RATIONALE_TEMPLATES,
    )

    conn4 = get_connection(DB_PATH)
    cur4 = conn4.cursor()

    for inv_id in demo_inv_ids:
        cur4.execute("""
            SELECT i.investigation_id, s.store_name, c.category_name,
                i.confidence_score, e.analyzer_name, e.analyzer_score
            FROM investigations i
            JOIN stores s ON i.store_id = s.store_id
            JOIN categories c ON i.category_id = c.category_id
            JOIN evidence e ON i.investigation_id = e.investigation_id
            WHERE i.investigation_id = ?
            AND e.rank = 1
            AND e.sufficient_data = 1
        """, (inv_id,))

        row = cur4.fetchone()

        if row:
            _, store, category, confidence, analyzer_name, analyzer_score = row

            action = ACTION_TEMPLATES.get(
                analyzer_name,
                "Review {category} performance at {store}"
            ).format(store=store, category=category)

            rationale = RATIONALE_TEMPLATES.get(
                analyzer_name,
                "Analyzer flagged this (score={score:.2f})."
            ).format(
                score=analyzer_score,
                analyzer_name=analyzer_name
            )

            priority = _priority_from_confidence(confidence)

            cur4.execute("""
                INSERT INTO recommendations (
                    investigation_id, action, priority, rationale, status
                ) VALUES (?, ?, ?, ?, ?)
            """, (
                inv_id,
                action,
                priority,
                rationale,
                "pending",
            ))

            conn4.commit()

    conn4.close()

    update_progress(94, "Phase 7 of 7: Preparing AI summaries...")

    conn2 = sqlite3.connect(DB_PATH)
    cur2 = conn2.cursor()

    cur2.execute("""
        SELECT i.investigation_id
        FROM investigations i
        JOIN recommendations r ON i.investigation_id = r.investigation_id
        WHERE i.source = 'demo_upload'
        AND i.investigation_id NOT IN (
            SELECT investigation_id FROM summaries
        )
        ORDER BY i.confidence_score DESC
        LIMIT 5
    """)

    top_ids = [row[0] for row in cur2.fetchall()]
    conn2.close()

    summaries_generated = 0

    for index, inv_id in enumerate(top_ids, start=1):
        update_progress(
            94 + int((index / max(len(top_ids), 1)) * 5),
            f"Phase 7 of 7: Generating AI summary {index} of {len(top_ids)}..."
        )

        result = generate_summary_for_one_investigation(inv_id, DB_PATH)

        if result["status"] == "OK":
            summaries_generated += 1

    return {
        "status": "OK",
        "investigations_created": total_investigations,
        "summaries_generated": summaries_generated,
        "errors": errors,
    }


st.title("🧪 Try It Yourself")
st.caption(
    "Upload your own retail CSV or use our sample dataset "
    "to run the full DecisionLens pipeline live."
)
st.divider()

with st.expander("📋 Required CSV columns"):
    st.markdown("""
    | Column | Required | Notes |
    |--------|----------|-------|
    | Date | ✅ Hard required | Any standard date format |
    | Store | ✅ Hard required | Store/Branch/Location/State/City |
    | Category | ✅ Hard required | Product category |
    | Product | ✅ Hard required | Product name |
    | Revenue | ✅ Hard required | Sales/Amount/Total |
    | Quantity | ✅ Hard required | Units sold |
    | Cost | ⚠️ Soft required | Enables profit analysis |
    | Region | ⚠️ Soft required | Enables region analyzer |
    """)

st.divider()

col1, col2 = st.columns(2)

with col1:
    st.subheader("Upload your CSV")
    uploaded_file = st.file_uploader("Choose a CSV file", type=["csv"])

with col2:
    st.subheader("Or use our sample dataset")
    st.caption("Synthetic retail data with 3 injected anomalies and deliberate messiness.")

    with open(SAMPLE_DATASET_PATH, "rb") as f:
        st.download_button(
            "⬇️ Download sample_dataset.csv",
            data=f,
            file_name="sample_dataset.csv",
            mime="text/csv",
        )

    use_sample = st.button(
        "▶️ Run pipeline on sample dataset",
        type="primary"
    )

st.divider()

csv_path = None

if use_sample:
    if st.session_state.get("last_csv_source") != "sample":
        st.session_state["demo_ran"] = False
        st.session_state["last_csv_source"] = "sample"

    csv_path = SAMPLE_DATASET_PATH

elif uploaded_file is not None:
    if st.session_state.get("last_csv_source") != uploaded_file.name:
        tmp = tempfile.NamedTemporaryFile(delete=False, suffix=".csv")
        tmp.write(uploaded_file.read())
        tmp.close()

        st.session_state["uploaded_csv_path"] = tmp.name
        st.session_state["demo_ran"] = False
        st.session_state["demo_result"] = None
        st.session_state["last_csv_source"] = uploaded_file.name

    csv_path = st.session_state.get("uploaded_csv_path")

if csv_path and not st.session_state.get("demo_ran"):
    with st.spinner("Clearing previous demo results..."):
        clear_demo_data()

        conn_reset = sqlite3.connect(DB_PATH)
        conn_reset.execute(
            "DELETE FROM sqlite_sequence WHERE name = 'investigations'"
        )
        conn_reset.execute(
            "INSERT INTO sqlite_sequence (name, seq) VALUES ('investigations', 214)"
        )
        conn_reset.commit()
        conn_reset.close()

    progress = st.progress(0, text="Starting pipeline...")

    def update_streamlit_progress(percent, message):
        progress.progress(percent, text=message)

    with st.spinner("Running DecisionLens pipeline..."):
        result = _run_live_pipeline(
            csv_path,
            progress_callback=update_streamlit_progress,
        )

    progress.progress(100, text="Complete!")

    st.session_state["demo_result"] = result
    st.session_state["demo_ran"] = True

if st.session_state.get("demo_ran"):
    result = st.session_state["demo_result"]

    if result["status"] == "OK":
        st.success("✅ Pipeline complete!")

        col1, col2, col3 = st.columns(3)

        with col1:
            st.metric("Investigations", result["investigations_created"])

        with col2:
            st.metric("AI Summaries", result["summaries_generated"])

        with col3:
            st.metric("Errors", len(result["errors"]))

        st.divider()
        st.subheader("Demo Results")

        df = get_events_table(source="demo_upload")

        if df.empty:
            st.warning("No investigations generated.")

        else:
            display_df = df.copy()

            display_df["confidence_score"] = display_df["confidence_score"].apply(
                lambda x: f"{x:.1%}"
            )

            display_df = display_df.rename(columns={
                "investigation_id": "ID",
                "store": "Store",
                "category": "Category",
                "period": "Week",
                "confidence_score": "Confidence",
                "evidence_coverage": "Coverage",
                "priority": "Priority",
            })

            display_df = display_df[
                ["ID", "Store", "Category", "Week", "Confidence", "Coverage", "Priority"]
            ]

            event = st.dataframe(
                display_df,
                use_container_width=True,
                hide_index=True,
                on_select="rerun",
                selection_mode="single-row",
            )

            selected_rows = event.selection.rows

            if selected_rows:
                selected_id = int(display_df.iloc[selected_rows[0]]["ID"])
                st.success(
                    f"Investigation #{selected_id} selected — full report below"
                )
                st.divider()
                _render_inline_detail(selected_id)

    else:
        st.error(f"Pipeline failed: {result['errors']}")